### PR TITLE
Update pose_cov_ops.h

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Projectredunimore** [comment]
Tolto riferimento a ROS2

**Comment by jlblancoc** [comment]
Hi!
In theory, with the current package it should compile in both ROS1 and ROS2, but it has limited testing so far. Any issue you detected to motivate the PR?

**Comment by Projectredunimore** [comment]
I'm sorry, I confused this repo with mine. I'm new to github and I still don't know how to use it properly so I made a mess.
Sorry.

**Comment by jlblancoc** [comment]
no problem!

**Pull request closed without merging**
